version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_measures_precovid_2018-10-01_age:
    run: ehrql:v1 generate-measures analysis/dataset_definition/measures_cohorts.py
      --output output/measures/precovid/age_measures_2018-10-01.csv.gz
      --
      --practice_measures
      --CS
      --Age
      --start_cohort 2018-10-01
    outputs:
      highly_sensitive:
        dataset: output/measures/precovid/age_measures_2018-10-01.csv.gz

  generate_measures_precovid_2022-10-01_age:
    run: ehrql:v1 generate-measures analysis/dataset_definition/measures_cohorts.py
      --output output/measures/precovid/age_measures_2022-10-01.csv.gz
      --
      --practice_measures
      --CS
      --Age
      --start_cohort 2022-10-01
    outputs:
      highly_sensitive:
        dataset: output/measures/precovid/age_measures_2022-10-01.csv.gz

  generate_dataset_precovid_2018-10-01:
    run: ehrql:v1 generate-dataset analysis/dataset_definition/measures_cohorts.py
      --output output/measures/precovid/dataset_2018-10-01.csv.gz
      --
      --patient_measures
      --start_cohort 2018-10-01
    outputs:
      highly_sensitive:
        dataset: output/measures/precovid/dataset_2018-10-01.csv.gz